{"name": "test_a5", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <ke21.test_case1.TestCase1 object at 0x000002516B03A6D8>\n\n    def test_a5(self):\n        print(\"2222222222222\")\n>       assert 1 == 2\nE       assert 1 == 2\n\nke21\\test_case1.py:33: AssertionError"}, "attachments": [{"name": "stdout", "source": "793d06d2-bbb4-47ad-9428-77dfac7369bb-attachment.txt", "type": "text/plain"}], "start": 1659146992263, "stop": 1659146992264, "uuid": "83fd1587-1b25-4e74-8fe5-b4be1c6bd42c", "historyId": "cf47205c3b9475ca96150e935ae62075", "testCaseId": "8e9827777fcecd6e902b2a77c664c463", "fullName": "ke21.test_case1.TestCase1#test_a5", "labels": [{"name": "feature", "value": "添加商品"}, {"name": "parentSuite", "value": "ke21"}, {"name": "suite", "value": "test_case1"}, {"name": "subSuite", "value": "TestCase1"}, {"name": "host", "value": "DESKTOP-7DB67S3"}, {"name": "thread", "value": "27340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "ke21.test_case1"}]}