{"name": "test_a5", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <ke21.test_case1.TestCase1 object at 0x000001F5E3D187B8>\n\n    def test_a5(self):\n        print(\"2222222222222\")\n>       assert 1 == 2\nE       assert 1 == 2\n\nke21\\test_case1.py:33: AssertionError"}, "attachments": [{"name": "stdout", "source": "bce3c712-592f-4c23-9aa7-8b78619434fe-attachment.txt", "type": "text/plain"}], "start": 1659147148869, "stop": 1659147148869, "uuid": "7e94e245-187b-4131-a7c9-0ce0c5c07790", "historyId": "cf47205c3b9475ca96150e935ae62075", "testCaseId": "8e9827777fcecd6e902b2a77c664c463", "fullName": "ke21.test_case1.TestCase1#test_a5", "labels": [{"name": "feature", "value": "添加商品"}, {"name": "parentSuite", "value": "ke21"}, {"name": "suite", "value": "test_case1"}, {"name": "subSuite", "value": "TestCase1"}, {"name": "host", "value": "DESKTOP-7DB67S3"}, {"name": "thread", "value": "28080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "ke21.test_case1"}]}